import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const I=({children})=><span className="ico">{children}</span>;
const icons={user:"◯",qr:"⌗",bell:"♧",phone:"☎",bank:"▤",self:"♙",wallet:"▣",gift:"◇",refer:"↗",store:"▦",history:"◷",ticket:"▱",recharge:"▯",dish:"◒",bolt:"ϟ",bike:"♢",car:"▰",plane:"✈",bus:"▥",train:"▤",hotel:"⌂",spark:"✦",home:"⌂",reward:"★"};
const A=({icon,label,go})=><button className="action" onClick={go}><I>{icons[icon]||"✦"}</I><span>{label}</span></button>;
const S=({icon,label,go})=><button className="service" onClick={go}><I>{icons[icon]||"✦"}</I><span>{label}</span></button>;
const Sec=({title,children})=><section><h2>{title}</h2>{children}</section>;
function App(){const[t,setT]=useState("");const go=x=>{setT(x);clearTimeout(window.tt);window.tt=setTimeout(()=>setT(""),1500)};const four=(items,cl="")=><div className={"grid four "+cl}>{items.map((x,i)=><A key={i} {...x} go={()=>go(x.label.replace(/<br\/>/g," "))}/>)}</div>;
return <main className="phone"><header><div className="profile"><div className="avatar">{icons.user}</div><div><b>Home⌄</b><small>59/220 jayanagar bangalore</small></div></div><div className="headicons"><button onClick={()=>go("QR scanner")}>{icons.qr}</button><button onClick={()=>go("Notifications")}>{icons.bell}<em>3</em></button><button onClick={()=>go("Search")}>⌕</button></div></header><div className="scroll"><div className="hero"><b>Explore payments, offers & more</b><div>━ ━ ━ ━ ━</div></div>
<Sec title="Transfer Money">{four([{icon:"phone",label:<>To Mobile<br/>Number</>},{icon:"bank",label:<>To Bank/<br/>UPI ID</>},{icon:"self",label:<>To Self<br/>Account</>},{icon:"qr",label:<>Check<br/>Balance</>}])}</Sec>
<Sec title="Receive Money"><button className="upi" onClick={()=>go("UPI ID copied")}>⌗ UPI ID: 8088481884@ybl <b>›</b></button></Sec>
<div className="triple"><S icon="wallet" label="PhonePe Wallet" go={()=>go("Wallet")}/><S icon="gift" label="Rewards" go={()=>go("Rewards")}/><S icon="refer" label="Refer & Get ₹50" go={()=>go("Referral")}/></div>
<Sec title="Apps by PhonePe">{four([{icon:"store",label:"Business"},{icon:"history",label:"Share Market"},{icon:"ticket",label:"Pincode"}],"three")}</Sec>
<Sec title="Recharge & Pay Bills"><button className="pill" onClick={()=>go("My Bills")}>My Bills</button>{four([{icon:"recharge",label:"Mobile Recharge"},{icon:"ticket",label:"Buy FASTag"},{icon:"dish",label:"DTH"},{icon:"bolt",label:"Electricity"}])}{four([{icon:"wallet",label:"Rent Payment"},{icon:"ticket",label:"Loan Repayment"},{icon:"dish",label:"Book A Cylinder"},{icon:"spark",label:"See All"}],"second")}</Sec>
<div className="lite"><span>UPI <b>LITE</b></span><strong>PIN-less Payments</strong><button onClick={()=>go("UPI Lite")}>TRY NOW</button></div>
<Sec title="Sponsored Links"><div className="ads">{["Rush Ludo","A23 Rummy","OneCard","Buddy Loan"].map((x,i)=><button onClick={()=>go(x)} key={x}><i>{x[0]}</i><span>{x}</span></button>)}</div></Sec>
<Sec title="Insurance">{four([{icon:"bike",label:"Bike"},{icon:"car",label:"Car"},{icon:"self",label:"Health"},{icon:"spark",label:"Accident"}])}{four([{icon:"ticket",label:"Term Life"},{icon:"plane",label:"Travel Insurance"},{icon:"history",label:"Insurance Renewal"},{icon:"spark",label:"See All"}],"second")}</Sec>
<Sec title="Travel Bookings">{four([{icon:"plane",label:"Flights"},{icon:"bus",label:"Bus"},{icon:"train",label:"Trains"},{icon:"hotel",label:"Hotels"}])}</Sec>
<Sec title="Switch">{four([{icon:"store",label:"Namma Metro"},{icon:"spark",label:"Dream11"},{icon:"reward",label:"Tata 1mg"},{icon:"spark",label:"See All"}])}</Sec>
<Sec title="Brand Vouchers">{four([{icon:"ticket",label:"App Store Code"},{icon:"ticket",label:"Amazon Voucher"},{icon:"ticket",label:"Flipkart"},{icon:"spark",label:"See All"}])}</Sec>
<Sec title="Brand Vouchers"><div className="ads">{["WinZO Ludo","Kotak811","MPL Ludo","OneCard"].map(x=><button onClick={()=>go(x)} key={x}><i>{x[0]}</i><span>{x}</span></button>)}</div></Sec>
</div><nav>{[[icons.home,"Home"],[icons.history,"History"],[icons.reward,"Rewards"],[icons.store,"Stores"]].map((x,i)=><button className={i===0?"on":""} onClick={()=>go(x[1])} key={x[1]}><span>{x[0]}</span><small>{x[1]}</small></button>)}</nav>{t&&<div className="toast">{t}</div>}</main>}createRoot(document.getElementById("root")).render(<App/>);